name: TOML/MITRE Validation

on:
  push:
       path:
        - '**.toml'

  workflow_dispatch:


jobs:
  elastic-detections-all:
    runs-on: ubuntu-latest
    env:
      ELASTIC_KEY: ${{ secrets.ELASTIC_KEY }} 

    steps: 
    - uses: actions/checkout@v4
    - name: Set up Python 3.14.3
      uses: actions/setup-python@v4
      with:
        python-version: '3.14.3'
    - run: pip install requests
    - run: python development/validation.py
    - run: python development/mitre.py
